defaults: ../../sft.yaml
sft:
  max_num_steps: 500
checkpointing:
  checkpoint_dir: results/sft-llama3.2-1b-1n8g-fsdp2tp1
  save_period: 100
policy:
  dtensor_cfg:
    lora:
      dim: 32
  tokenizer:
    name: meta-llama/Llama-3.2-1B
  make_sequence_length_divisible_by: 1
data:
  dataset_name: openmathinstruct2
  prompt_file: examples/prompts/math.txt
  split: train_1M
  add_generation_prompt: true
  output_key: generated_solution
  seed: 42
logger:
  log_dir: logs/sft-llama3.2-1b-1n8g-fsdp2tp1
  wandb:
    project: nemo-rl
    name: sft-llama3.2-1b-1n8g-fsdp2tp1
  tensorboard:
    log_dir: tb_logs-sft-dev-openmathinstruct2
cluster:
  gpus_per_node: 8
