defaults: ../../sft.yaml
sft:
  max_num_epochs: 3
  max_num_steps: 100
  val_global_batch_size: 128
checkpointing:
  checkpoint_dir: results/sft-nemotron-super-49b
  metric_name: val:loss
  keep_top_k: 100
  save_period: 500
policy:
  model_name: /lustre/fsw/portfolios/coreai/users/joyang/models/llama-3_3-nemotron-49b-instruct-128k-v1_2-hf
  max_total_sequence_length: 4096
  train_global_batch_size: 128
  train_micro_batch_size: 8
  dtensor_cfg:
    _v2: true
    activation_checkpointing: true
    context_parallel_size: 2
    tensor_parallel_size: 4
    custom_parallel_plan: examples.custom_parallel.llama_nemotron_super_49b_custom_plan.custom_parallel_plan
  dynamic_batching:
    train_mb_tokens: 4096
    logprob_mb_tokens: 8192
  make_sequence_length_divisible_by: ${max:${mul:${policy.dtensor_cfg.context_parallel_size},
    2}, ${policy.max_total_sequence_length}}
  max_grad_norm: null
  optimizer:
    kwargs:
      lr: 2.0e-05
      weight_decay: 0.01
      eps: 1.0e-08
data:
  num_workers: 20
logger:
  tensorboard_enabled: false
  monitor_gpus: false
  num_val_samples_to_print: 0
  wandb:
    project: sft-nemotron
    name: sft-${data.dataset_name}-nemotron-super-49b
  tensorboard:
    log_dir: tb_logs-openmathinstruct-nemorl-1M_train
  mlflow:
    experiment_name: sft-nemotron-super-49b
    run_name: openmathinstruct-nemorl-1M_train
cluster:
  gpus_per_node: 8
