defaults: ../../../grpo_math_1B.yaml
grpo:
  num_prompts_per_step: 64
  num_generations_per_prompt: 32
checkpointing:
  enabled: false
  checkpoint_dir: results/grpo-qwen3-30ba3b-4n8g
policy:
  model_name: Qwen/Qwen3-30B-A3B
  train_micro_batch_size: 1
  max_total_sequence_length: 4096
  dtensor_cfg:
    enabled: false
  optimizer: null
  scheduler: null
  make_sequence_length_divisible_by: ${policy.megatron_cfg.tensor_model_parallel_size}
  megatron_cfg:
    enabled: true
    empty_unused_memory_level: 1
    tensor_model_parallel_size: 1
    pipeline_model_parallel_size: 1
    expert_model_parallel_size: 8
    sequence_parallel: false
    optimizer:
      lr: 3.0e-07
      min_lr: 3.0e-08
    scheduler:
      lr_warmup_iters: 50
      lr_warmup_init: 3.0e-08
    env_vars:
      PYTORCH_CUDA_ALLOC_CONF: expandable_segments:False
  generation:
    vllm_cfg:
      tensor_parallel_size: 2
logger:
  log_dir: logs/grpo-qwen3-30ba3b-4n8g
  wandb_enabled: true
  tensorboard_enabled: true
  wandb:
    project: nemo-rl
    name: grpo-qwen3-30ba3b-4n8g
cluster:
  gpus_per_node: 8
  num_nodes: 4
