defaults: ./grpo-qwen3-235b-16n8g.yaml
grpo:
  async_grpo:
    enabled: true
    max_trajectory_age_steps: 1
    in_flight_weight_updates: true
loss_fn:
  use_importance_sampling_correction: true
checkpointing:
  checkpoint_dir: results/grpo-qwen3-235b-32n8g-async-1off
policy:
  megatron_cfg:
    tensor_model_parallel_size: 4
    sequence_parallel: true
    context_parallel_size: 1
    pipeline_model_parallel_size: 8
    expert_model_parallel_size: 16
    defer_fp32_logits: false
  generation:
    colocated:
      enabled: false
      resources:
        num_nodes: 16
        gpus_per_node: 8
    vllm_cfg:
      tensor_parallel_size: 8
      gpu_memory_utilization: 0.8
      async_engine: true
logger:
  log_dir: logs/grpo-qwen3-235b-32n8g-16T16G-async-1off
  wandb:
    name: grpo-qwen3-235b-32n8g-16T16G-async-1off
cluster:
  gpus_per_node: 8
  num_nodes: 32
